-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, 
count(*) as RECORDS
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
where START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
and CAR_ID in(
select CAR_ID
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
where START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
group by CAR_ID
having count(*)>=5)
group by DATE_FORMAT(START_DATE, '%m'), CAR_ID
order by 1, 2 desc;