-- 코드를 입력하세요
SELECT distinct C.CAR_ID
from CAR_RENTAL_COMPANY_CAR c
join CAR_RENTAL_COMPANY_RENTAL_HISTORY  h
on C.CAR_ID = H.CAR_ID
where C.CAR_TYPE = '세단'
AND MONTH(H.START_DATE) = 10
ORDER BY C.CAR_ID DESC;